/* ==========================================================================
   French vocabulary data
   Each entry: { unit, lesson, category, fr, en }
   Grammar is kept separate (see GRAMMAR at the bottom) so you can fill it in.
   ========================================================================== */

const VOCAB = [
  /* ===================== UNITÉ PRÉLIMINAIRE ===================== */
  // Les présentations
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Bonjour.", en: "Hello." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Bonsoir.", en: "Good evening." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "C'est le premier mai/le dix juillet.", en: "It's on May 1st/July 10th." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Comment écrit-on... ?", en: "How do you write...?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Comment t'appelles-tu/vous appelez-vous?", en: "What is your name?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "De même.", en: "Likewise." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Enchanté(e).", en: "It's a pleasure." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Et toi/vous?", en: "And you?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "J'ai... ans.", en: "I am... years old." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Je m'appelle...", en: "My name is..." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "le nom", en: "last name" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "non", en: "no" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "oui", en: "yes" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "le prénom", en: "first name" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Quel âge as-tu/avez-vous?", en: "How old are you?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Quelle est la date de l'anniversaire de Thomas?/C'est quand l'anniversaire de Thomas?", en: "When is Thomas' birthday?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Quelle est la date de ton/votre anniversaire?/C'est quand ton/votre anniversaire?", en: "When is your birthday?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Ravi(e).", en: "Delighted." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Salut.", en: "Hi." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Tu es de quelle nationalité?", en: "What is your nationality?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "J'ai...", en: "I have..." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les présentations", fr: "Tu as...", en: "You have..." },
  // Les personnes
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les personnes", fr: "la fille", en: "girl" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les personnes", fr: "le garçon", en: "boy" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les personnes", fr: "madame (Mme)", en: "Ms., Mrs." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les personnes", fr: "mademoiselle (Mlle)", en: "Miss" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les personnes", fr: "monsieur (M.)", en: "Mr." },
  // Être
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Être", fr: "je suis", en: "I am" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Être", fr: "tu es", en: "you are" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Être", fr: "il/elle est", en: "he/she is" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Être", fr: "elle est", en: "she is" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Être", fr: "nous sommes", en: "we are" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Être", fr: "vous êtes", en: "you are" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Être", fr: "ils/elles sont", en: "they are" },
  // Les pays
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "l'Algérie (f.)", en: "Algeria" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "la Belgique", en: "Belgium" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "le Canada", en: "Canada" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "la capitale", en: "capital city" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "le drapeau", en: "flag" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "les États-Unis", en: "United States" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "la France", en: "France" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "Haïti (m.)", en: "Haiti" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "le Mali", en: "Mali" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "le Maroc", en: "Morocco" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "le Québec", en: "Quebec" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "le Sénégal", en: "Senegal" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "la Suisse", en: "Switzerland" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "la Tunisie", en: "Tunisia" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les pays", fr: "le Viêt-Nam", en: "Vietnam" },
  // Les nationalités
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "algérien(ne)", en: "Algerian" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "américain(e)", en: "American" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "belge", en: "Belgian" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "canadien(ne)", en: "Canadian" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "français(e)", en: "French" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "haïtien(ne)", en: "Haitian" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "malien(ne)", en: "Malian" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "marocain(e)", en: "Moroccan" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "québécois(e)", en: "Quebecois" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "sénégalais(e)", en: "Senegalese" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "suisse", en: "Swiss" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "tunisien(ne)", en: "Tunisian" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les nationalités", fr: "vietnamien(ne)", en: "Vietnamese" },
  // Les mois
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "janvier", en: "January" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "février", en: "February" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "mars", en: "March" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "avril", en: "April" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "mai", en: "May" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "juin", en: "June" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "juillet", en: "July" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "août", en: "August" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "septembre", en: "September" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "octobre", en: "October" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "novembre", en: "November" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les mois", fr: "décembre", en: "December" },
  // Identifier
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Identifier", fr: "C'est...", en: "It is..." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Identifier", fr: "combien (de)", en: "how many" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Identifier", fr: "des", en: "some" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Identifier", fr: "il y a", en: "there is/are" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Identifier", fr: "Qu'est-ce que c'est?", en: "What is it?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Identifier", fr: "un(e)", en: "a, an" },
  // La salle de classe
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "une calculatrice", en: "calculator" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "un dictionnaire", en: "dictionary" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "un(e) élève", en: "student, pupil" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "un livre", en: "book" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "un ordinateur", en: "laptop computer" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "un(e) professeur", en: "teacher" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "un stylo", en: "pen" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "une table", en: "table" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "un tableau", en: "black/whiteboard" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "une tablette", en: "tablet" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "La salle de classe", fr: "une télévision", en: "television" },
  // Les matières
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "le cours", en: "course/class" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "l'anglais (m.)", en: "English" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "l'art (m.)", en: "art" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "l'espagnol (m.)", en: "Spanish" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "le français", en: "French" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "la géographie", en: "geography" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "l'histoire (f.)", en: "history" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "l'informatique (f.)", en: "computer science" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "les langues (f.)", en: "languages" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "la littérature", en: "literature" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "les mathématiques/maths (f.)", en: "math" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "la musique", en: "music" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les matières", fr: "les sciences (f.)", en: "sciences" },
  // Les jours de la semaine
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les jours de la semaine", fr: "lundi", en: "Monday" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les jours de la semaine", fr: "mardi", en: "Tuesday" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les jours de la semaine", fr: "mercredi", en: "Wednesday" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les jours de la semaine", fr: "jeudi", en: "Thursday" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les jours de la semaine", fr: "vendredi", en: "Friday" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les jours de la semaine", fr: "samedi", en: "Saturday" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "Les jours de la semaine", fr: "dimanche", en: "Sunday" },
  // L'emploi du temps
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "après", en: "after" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "après-demain", en: "day after tomorrow" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "l'après-midi", en: "(in the) afternoon" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "Aujourd'hui, c'est...", en: "Today is..." },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "le déjeuner", en: "lunch" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "demain", en: "tomorrow" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "hier", en: "yesterday" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "l'interro(gation) (f.)", en: "quiz, test" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "le matin", en: "(in the) morning" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "Quel jour sommes-nous?", en: "What day is it today?" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "la semaine", en: "week" },
  { unit: "Unité préliminaire", lesson: "Prélim", category: "L'emploi du temps", fr: "le soir", en: "(in the) evening" },

  /* ===================== LEÇON 1A ===================== */
  // Bonjour et au revoir
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "À bientôt.", en: "See you soon." },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "À demain.", en: "See you tomorrow." },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "À plus tard.", en: "See you later." },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "À tout à l'heure.", en: "See you later." },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "Au revoir.", en: "Good-bye." },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "Bonne journée!", en: "Have a good day!" },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "Bonjour.", en: "Good morning.; Hello." },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "Bonsoir.", en: "Good evening.; Hello." },
  { unit: "Unité 1", lesson: "1A", category: "Bonjour et au revoir", fr: "Salut!", en: "Hi!; Bye!" },
  // Comment ça va?
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Ça va?", en: "What's up?; How are things?" },
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Comment allez-vous? (form.)", en: "How are you?" },
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Comment vas-tu? (fam.)", en: "How are you?" },
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Comme ci, comme ça.", en: "So-so." },
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Je vais bien/mal.", en: "I am doing well/badly." },
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Moi aussi.", en: "Me too." },
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Pas mal.", en: "Not badly." },
  { unit: "Unité 1", lesson: "1A", category: "Comment ça va?", fr: "Très bien.", en: "Very well." },
  // Expressions de politesse
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "De rien.", en: "You're welcome." },
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "Il n'y a pas de quoi.", en: "It's nothing; You're welcome." },
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "Je vous en prie. (form.)", en: "Please.; You're welcome." },
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "Merci beaucoup.", en: "Thank you very much." },
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "Monsieur (M.)", en: "Sir (Mr.)" },
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "Madame (Mme)", en: "Ma'am (Mrs.)" },
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "Mademoiselle (Mlle)", en: "Miss" },
  { unit: "Unité 1", lesson: "1A", category: "Expressions de politesse", fr: "S'il vous plaît. (form./fam.)", en: "Please." },
  // Les présentations
  { unit: "Unité 1", lesson: "1A", category: "Les présentations", fr: "Comment vous appelez-vous? (form.)", en: "What is your name?" },
  { unit: "Unité 1", lesson: "1A", category: "Les présentations", fr: "Comment t'appelles-tu? (fam.)", en: "What is your name?" },
  { unit: "Unité 1", lesson: "1A", category: "Les présentations", fr: "Enchanté(e).", en: "Delighted." },
  { unit: "Unité 1", lesson: "1A", category: "Les présentations", fr: "Et vous/toi? (form./fam.)", en: "And you?" },
  { unit: "Unité 1", lesson: "1A", category: "Les présentations", fr: "Je m'appelle...", en: "My name is..." },
  { unit: "Unité 1", lesson: "1A", category: "Les présentations", fr: "Je vous/te présente...", en: "I would like to introduce (name) to you." },
  // Le campus
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "une bibliothèque", en: "library" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "une librairie", en: "bookstore" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "un lycée", en: "high school" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "un examen", en: "exam, test" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "un bureau", en: "desk; office" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "un ordinateur", en: "computer" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "un tableau", en: "blackboard; painting" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "une chose", en: "thing" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "un objet", en: "object" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "l'histoire (f.)", en: "History; story" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "une tablette", en: "tablet (tech.)" },
  { unit: "Unité 1", lesson: "1A", category: "Le campus", fr: "un téléphone (portable)", en: "(cell) phone" },
  // Les personnes
  { unit: "Unité 1", lesson: "1A", category: "Les personnes", fr: "un(e) ami(e)", en: "friend" },
  { unit: "Unité 1", lesson: "1A", category: "Les personnes", fr: "un(e) étudiant(e)", en: "student" },
  { unit: "Unité 1", lesson: "1A", category: "Les personnes", fr: "une personne", en: "person" },
  { unit: "Unité 1", lesson: "1A", category: "Les personnes", fr: "un acteur/une actrice", en: "actor" },
  { unit: "Unité 1", lesson: "1A", category: "Les personnes", fr: "un chanteur/une chanteuse", en: "singer" },
  // Identifier
  { unit: "Unité 1", lesson: "1A", category: "Identifier", fr: "c'est/ce sont", en: "it's/they are" },
  { unit: "Unité 1", lesson: "1A", category: "Identifier", fr: "Combien...?", en: "How much/many...?" },
  { unit: "Unité 1", lesson: "1A", category: "Identifier", fr: "Il y a...", en: "There is/are..." },
  { unit: "Unité 1", lesson: "1A", category: "Identifier", fr: "Qu'est-ce que c'est?", en: "What is it?" },
  { unit: "Unité 1", lesson: "1A", category: "Identifier", fr: "Qui est-ce?", en: "Who is this?" },
  { unit: "Unité 1", lesson: "1A", category: "Identifier", fr: "voici", en: "here is/are" },
  { unit: "Unité 1", lesson: "1A", category: "Identifier", fr: "voilà", en: "here is/are" },

  /* ===================== LEÇON 1B ===================== */
  // En classe
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une salle de classe", en: "classroom" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "un livre", en: "book" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une carte", en: "map" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une chaise", en: "chair" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une fenêtre", en: "window" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une horloge", en: "clock" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une porte", en: "door" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "un cahier", en: "notebook" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une calculatrice", en: "calculator" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "un crayon", en: "pencil" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une feuille de papier", en: "sheet of paper" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "un sac à dos", en: "backpack" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "un stylo", en: "pen" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une gomme", en: "eraser" },
  { unit: "Unité 1", lesson: "1B", category: "En classe", fr: "une trousse", en: "pencil case" },
  // Les personnes
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "un copain/une copine (fam.)", en: "friend" },
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "un(e) élève", en: "pupil, student" },
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "un(e) enseignant(e)", en: "a teacher" },
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "une femme", en: "woman" },
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "une fille", en: "girl" },
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "un garçon", en: "boy" },
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "un homme", en: "man" },
  { unit: "Unité 1", lesson: "1B", category: "Les personnes", fr: "un(e) professeur", en: "teacher, professor" },
  // Identifier
  { unit: "Unité 1", lesson: "1B", category: "Identifier", fr: "Qui est-ce?", en: "Who is it?" },
  { unit: "Unité 1", lesson: "1B", category: "Identifier", fr: "Qu'est-ce que c'est?", en: "What is it?" },
  // Subject pronouns
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "je", en: "I" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "tu", en: "you" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "il", en: "he/it (masc.)" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "elle", en: "she/it (fem.)" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "on", en: "one" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "nous", en: "we" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "vous", en: "you" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "ils", en: "they (masc.)" },
  { unit: "Unité 1", lesson: "1B", category: "Subject pronouns", fr: "elles", en: "they (fem.)" },
  // Être
  { unit: "Unité 1", lesson: "1B", category: "Être", fr: "je suis", en: "I am" },
  { unit: "Unité 1", lesson: "1B", category: "Être", fr: "tu es", en: "you are" },
  { unit: "Unité 1", lesson: "1B", category: "Être", fr: "il/elle est", en: "he/she/it is" },
  { unit: "Unité 1", lesson: "1B", category: "Être", fr: "on est", en: "one is" },
  { unit: "Unité 1", lesson: "1B", category: "Être", fr: "nous sommes", en: "we are" },
  { unit: "Unité 1", lesson: "1B", category: "Être", fr: "vous êtes", en: "you are" },
  { unit: "Unité 1", lesson: "1B", category: "Être", fr: "ils/elles sont", en: "they are" },
  // Descriptive adjectives
  { unit: "Unité 1", lesson: "1B", category: "Descriptive adjectives", fr: "agréable", en: "pleasant" },
  { unit: "Unité 1", lesson: "1B", category: "Descriptive adjectives", fr: "amical(e)", en: "friendly" },
  { unit: "Unité 1", lesson: "1B", category: "Descriptive adjectives", fr: "désagréable", en: "unpleasant" },
  { unit: "Unité 1", lesson: "1B", category: "Descriptive adjectives", fr: "impoli(e)", en: "impolite, rude" },
  { unit: "Unité 1", lesson: "1B", category: "Descriptive adjectives", fr: "occupé(e)", en: "busy" },
  { unit: "Unité 1", lesson: "1B", category: "Descriptive adjectives", fr: "poli(e)", en: "polite" },
  { unit: "Unité 1", lesson: "1B", category: "Descriptive adjectives", fr: "sympathique (sympa)", en: "nice" },
  // Adjectives of nationality
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "allemand(e)", en: "German" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "anglais(e)", en: "English" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "chinois(e)", en: "Chinese" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "coréen(ne)", en: "Korean" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "cubain(e)", en: "Cuban" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "espagnol(e)", en: "Spanish" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "indien(ne)", en: "Indian" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "irlandais(e)", en: "Irish" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "japonais(e)", en: "Japanese" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "martiniquais(e)", en: "from Martinique" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "polonais(e)", en: "Polish" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "portugais(e)", en: "Portugese" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "québécois(e)", en: "from Quebec" },
  { unit: "Unité 1", lesson: "1B", category: "Adjectives of nationality", fr: "russe", en: "Russian" },

  /* ===================== LEÇON 2A ===================== */
  // Les cours
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "la chimie", en: "chemistry" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "l'informatique (f.)", en: "computer science" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "les langues (étrangères) (f.)", en: "(foreign) languages" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "la physique", en: "physics" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "la cantine", en: "cafeteria" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "un cours", en: "class, course" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "un devoir; les devoirs", en: "homework" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "l'école (f.)", en: "school" },
  { unit: "Unité 2", lesson: "2A", category: "Les cours", fr: "une note", en: "grade" },
  // Adjectifs et adverbes
  { unit: "Unité 2", lesson: "2A", category: "Adjectifs et adverbes", fr: "difficile", en: "difficult" },
  { unit: "Unité 2", lesson: "2A", category: "Adjectifs et adverbes", fr: "facile", en: "easy" },
  { unit: "Unité 2", lesson: "2A", category: "Adjectifs et adverbes", fr: "inutile", en: "useless" },
  { unit: "Unité 2", lesson: "2A", category: "Adjectifs et adverbes", fr: "utile", en: "useful" },
  // Vocabulaire supplémentaire
  { unit: "Unité 2", lesson: "2A", category: "Vocabulaire supplémentaire", fr: "J'aime bien...", en: "I like..." },
  { unit: "Unité 2", lesson: "2A", category: "Vocabulaire supplémentaire", fr: "Je n'aime pas tellement...", en: "I don't like... very much." },
  // Verbes
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "aimer", en: "to like; to love" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "aimer mieux", en: "to prefer" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "chercher", en: "to look for" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "commencer", en: "to begin, to start" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "dessiner", en: "to draw; to design" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "donner", en: "to give" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "étudier", en: "to study" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "habiter (à)", en: "to live (in)" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "manger", en: "to eat" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "oublier", en: "to forget" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "parler (au téléphone)", en: "to speak (on the phone)" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "partager", en: "to share" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "penser (que/qu')", en: "to think (that)" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "regarder", en: "to look (at), to watch" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "rencontrer", en: "to meet" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "retrouver", en: "to meet up with; to find (again)" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "travailler", en: "to work" },
  { unit: "Unité 2", lesson: "2A", category: "Verbes", fr: "voyager", en: "to travel" },
  // Des questions et des opinions
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "bien sûr", en: "of course" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "d'accord", en: "OK, all right" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "Est-ce que/qu'...?", en: "Question phrase" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "(mais) non", en: "no (but of course not)" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "moi/toi non plus", en: "me/you neither" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "ne... pas", en: "no, not" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "n'est-ce pas?", en: "isn't that right?" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "oui/si", en: "yes" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "parce que", en: "because" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "pas du tout", en: "not at all" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "peut-être", en: "maybe, perhaps" },
  { unit: "Unité 2", lesson: "2A", category: "Des questions et des opinions", fr: "Pourquoi?", en: "Why?" },

  /* ===================== LEÇON 2B ===================== */
  // Les cours
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "assister à", en: "to attend" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "demander", en: "to ask" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "échouer", en: "to fail" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "écouter", en: "to listen (to)" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "enseigner", en: "to teach" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "expliquer", en: "to explain" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "passer un examen", en: "to take an exam" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "préparer", en: "to prepare (for)" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "rentrer (à la maison)", en: "to return (home)" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "trouver", en: "to find; to think" },
  { unit: "Unité 2", lesson: "2B", category: "Les cours", fr: "visiter", en: "to visit (a place)" },
  // Expressions de temps
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "un an", en: "a year" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "une/cette année", en: "one/this year" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "après", en: "after" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "un/cet après-midi", en: "an/this afternoon" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "un jour", en: "a day" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "une journée", en: "a day" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "un/ce matin", en: "a/this morning" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "un mois/ce mois-ci", en: "a month/this month" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "une/cette nuit", en: "a/this night" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "une/cette semaine", en: "a/this week" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "un/ce soir", en: "an/this evening" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "une soirée", en: "an evening" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "dernier/dernière", en: "last" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "premier/première", en: "first" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "prochain(e)", en: "next" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions de temps", fr: "tous les jours", en: "every day" },
  // Expressions avec avoir
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir", en: "to have" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir... ans", en: "to be... years old" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir besoin (de)", en: "to need" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir chaud", en: "to be hot" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir de bonnes/mauvaises notes", en: "to have good/bad grades" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir envie (de)", en: "to feel like" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir froid", en: "to be cold" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir peur (de)", en: "to be afraid (of)" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir raison", en: "to be right" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir sommeil", en: "to be sleepy" },
  { unit: "Unité 2", lesson: "2B", category: "Expressions avec avoir", fr: "avoir tort", en: "to be wrong" },
  // L'heure
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "Quelle heure est-il?", en: "What time is it?" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "Il est... heures.", en: "It is... o'clock." },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "une heure", en: "one o'clock" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "et quart", en: "fifteen minutes past the hour" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "et demie", en: "thirty minutes past the hour" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "moins dix", en: "ten minutes before the hour" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "moins le quart", en: "fifteen minutes before the hour" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "À quelle heure?", en: "(At) what time/when?" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "de l'après-midi", en: "in the afternoon" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "du matin", en: "in the morning" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "du soir", en: "in the evening" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "en avance", en: "early" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "en retard", en: "late" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "midi", en: "noon" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "minuit", en: "midnight" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "pile", en: "sharp, on the dot" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "presque", en: "almost" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "tard", en: "late" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "tôt", en: "early" },
  { unit: "Unité 2", lesson: "2B", category: "L'heure", fr: "vers", en: "about" },

  /* ===================== LEÇON 3A ===================== */
  // La famille
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un beau-frère", en: "brother-in-law" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un beau-père", en: "father-in-law; stepfather" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une belle-mère", en: "mother-in-law; stepmother" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une belle-sœur", en: "sister-in-law" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un demi-frère", en: "half-brother; stepbrother" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une demi-sœur", en: "half-sister; stepsister" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "les enfants (m., f.)", en: "children" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "(un enfant) unique", en: "only (child)" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une femme", en: "wife; woman" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une fille", en: "daughter; girl" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un fils", en: "son" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un frère", en: "brother" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une grand-mère", en: "grandmother" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un grand-père", en: "grandfather" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un mari", en: "husband" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une mère", en: "mother" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un neveu", en: "nephew" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un père", en: "father" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une petite-fille", en: "granddaughter" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un petit-fils", en: "grandson" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "les petits-enfants (m.)", en: "grandchildren" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une sœur", en: "sister" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "une tante", en: "aunt" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un chat", en: "cat" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un chien", en: "dog" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un oiseau", en: "bird" },
  { unit: "Unité 3", lesson: "3A", category: "La famille", fr: "un poisson", en: "fish" },
  // Vocabulaire supplémentaire
  { unit: "Unité 3", lesson: "3A", category: "Vocabulaire supplémentaire", fr: "aîné(e)", en: "elder" },
  { unit: "Unité 3", lesson: "3A", category: "Vocabulaire supplémentaire", fr: "cadet(te)", en: "younger" },
  { unit: "Unité 3", lesson: "3A", category: "Vocabulaire supplémentaire", fr: "célibataire", en: "single" },
  { unit: "Unité 3", lesson: "3A", category: "Vocabulaire supplémentaire", fr: "veuf/veuve", en: "widowed" },
  { unit: "Unité 3", lesson: "3A", category: "Vocabulaire supplémentaire", fr: "un(e) voisin(e)", en: "neighbor" },
  // Adjectifs descriptifs
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "blanc(he)", en: "white" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "bleu(e)", en: "blue" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "brun(e)", en: "dark (hair)" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "court(e)", en: "short" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "grand(e)", en: "big; tall" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "gris(e)", en: "grey" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "jeune", en: "young" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "joli(e)", en: "pretty" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "laid(e)", en: "ugly" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "mauvais(e)", en: "bad" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "noir(e)", en: "black" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "vert(e)", en: "green" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs descriptifs", fr: "de taille moyenne", en: "medium-sized" },
  // Adjectifs irréguliers
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "beau/belle", en: "beautiful; handsome" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "bon(ne)", en: "kind; good" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "châtain", en: "brown (hair)" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "fier/fière", en: "proud" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "gros(se)", en: "fat" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "intellectuel(le)", en: "intellectual" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "(mal)heureux/(mal)heureuse", en: "(un)happy" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "long(ue)", en: "long" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "marron", en: "brown (not for hair)" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "naïf/naïve", en: "naïve" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "nouveau/nouvelle", en: "new" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "roux/rousse", en: "red-haired" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs irréguliers", fr: "vieux/vieille", en: "old" },
  // Adjectifs possessifs
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs possessifs", fr: "mon, ma, mes", en: "my" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs possessifs", fr: "ton, ta, tes", en: "your (fam. and sing.)" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs possessifs", fr: "son, sa, ses", en: "his, her, its" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs possessifs", fr: "notre, notre, nos", en: "our" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs possessifs", fr: "votre, votre, vos", en: "your (form. or pl.)" },
  { unit: "Unité 3", lesson: "3A", category: "Adjectifs possessifs", fr: "leur, leur, leurs", en: "their" },

  /* ===================== LEÇON 3B ===================== */
  // Adjectifs descriptifs
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "drôle", en: "funny" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "faible", en: "weak" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "fort(e)", en: "strong" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "génial(e) (géniaux m., pl.)", en: "great" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "lent(e)", en: "slow" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "méchant(e)", en: "mean" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "pénible", en: "annoying" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs descriptifs", fr: "triste", en: "sad" },
  // Professions et occupations
  { unit: "Unité 3", lesson: "3B", category: "Professions et occupations", fr: "un(e) avocat(e)", en: "lawyer" },
  { unit: "Unité 3", lesson: "3B", category: "Professions et occupations", fr: "un coiffeur/une coiffeuse", en: "hairdresser" },
  { unit: "Unité 3", lesson: "3B", category: "Professions et occupations", fr: "un homme/une femme d'affaires", en: "businessman/woman" },
  { unit: "Unité 3", lesson: "3B", category: "Professions et occupations", fr: "un(e) ingénieur", en: "engineer" },
  { unit: "Unité 3", lesson: "3B", category: "Professions et occupations", fr: "un médecin", en: "doctor" },
  // Adjectifs irréguliers
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs irréguliers", fr: "ennuyeux/ennuyeuse", en: "boring" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs irréguliers", fr: "fou/folle", en: "crazy" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs irréguliers", fr: "gentil(le)", en: "nice" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs irréguliers", fr: "inquiet/inquiète", en: "worried" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs irréguliers", fr: "jaloux/jalouse", en: "jealous" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs irréguliers", fr: "paresseux/paresseuse", en: "lazy" },
  { unit: "Unité 3", lesson: "3B", category: "Adjectifs irréguliers", fr: "travailleur/travailleuse", en: "hard-working" },
  // Prépositions de lieu
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "à côté de", en: "next to" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "à droite de", en: "to the right of" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "à gauche de", en: "to the left of" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "dans", en: "in" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "derrière", en: "behind" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "devant", en: "in front of" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "en", en: "in" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "en face de", en: "facing, across from" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "entre", en: "between" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "loin de", en: "far from" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "par", en: "by" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "près de", en: "close to, near" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "sous", en: "under" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "sur", en: "on" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "chez", en: "at/to someone's house/place" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "juste", en: "just, right" },
  { unit: "Unité 3", lesson: "3B", category: "Prépositions de lieu", fr: "tout", en: "very, really" },
  // Pronoms disjoints
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "moi", en: "me" },
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "toi", en: "you" },
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "lui", en: "him" },
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "elle", en: "her" },
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "nous", en: "us" },
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "vous", en: "you" },
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "eux", en: "them" },
  { unit: "Unité 3", lesson: "3B", category: "Pronoms disjoints", fr: "elles", en: "them" },

  /* ===================== LEÇON 4A ===================== */
  // Dans la ville
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un bureau", en: "office; desk" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un centre commercial", en: "shopping center, mall" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "une église", en: "church" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "une épicerie", en: "grocery store" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un (grand) magasin", en: "(department) store" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "une maison", en: "house" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un musée", en: "museum" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un (super) marché", en: "(super) market" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "une piscine", en: "pool" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "une place", en: "square; place" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un centre-ville", en: "city/town center, downtown" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un endroit", en: "place" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "un lieu", en: "place" },
  { unit: "Unité 4", lesson: "4A", category: "Dans la ville", fr: "une ville", en: "city, town" },
  // Activités
  { unit: "Unité 4", lesson: "4A", category: "Activités", fr: "bavarder", en: "to chat" },
  { unit: "Unité 4", lesson: "4A", category: "Activités", fr: "danser", en: "to dance" },
  { unit: "Unité 4", lesson: "4A", category: "Activités", fr: "déjeuner", en: "to eat lunch" },
  { unit: "Unité 4", lesson: "4A", category: "Activités", fr: "dépenser de l'argent (m.)", en: "to spend money" },
  { unit: "Unité 4", lesson: "4A", category: "Activités", fr: "nager", en: "to swim" },
  { unit: "Unité 4", lesson: "4A", category: "Activités", fr: "passer chez quelqu'un", en: "to stop by someone's house" },
  { unit: "Unité 4", lesson: "4A", category: "Activités", fr: "quitter la maison", en: "to leave the house" },
  // Verbes
  { unit: "Unité 4", lesson: "4A", category: "Verbes", fr: "aller", en: "to go" },
  { unit: "Unité 4", lesson: "4A", category: "Verbes", fr: "commencer à + [infinitive]", en: "to start (doing something)" },
  { unit: "Unité 4", lesson: "4A", category: "Verbes", fr: "penser à", en: "to think about" },
  { unit: "Unité 4", lesson: "4A", category: "Verbes", fr: "téléphoner à", en: "to phone (someone)" },
  // Prépositions
  { unit: "Unité 4", lesson: "4A", category: "Prépositions", fr: "à [+ definite article]", en: "to, in, at" },
  { unit: "Unité 4", lesson: "4A", category: "Prépositions", fr: "dans", en: "inside; within" },
  // Les questions
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "à quelle heure?", en: "at what time?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "à qui?", en: "to whom?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "avec qui?", en: "with whom?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "combien (de)?", en: "how many?; how much?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "comment?", en: "how?; what?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "où?", en: "where?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "parce que", en: "because" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "pour qui?", en: "for whom?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "pourquoi?", en: "why?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "quand?", en: "when?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "quel(le)(s)?", en: "which?; what?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "que/qu'...?", en: "what?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "qui?", en: "who?; whom?" },
  { unit: "Unité 4", lesson: "4A", category: "Les questions", fr: "quoi?", en: "what?" },

  /* ===================== LEÇON 4B ===================== */
  // À table
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "avoir faim", en: "to be hungry" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "avoir soif", en: "to be thirsty" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "manger", en: "to eat" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "une baguette", en: "baguette (long, thin loaf of bread)" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "un croque-monsieur", en: "a warm ham and cheese sandwich" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "un éclair", en: "éclair (pastry filled with cream)" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "des frites (f.)", en: "French fries" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "un fromage", en: "cheese" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "le jambon", en: "ham" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "un pain (de campagne)", en: "(country-style) bread" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "le sucre", en: "sugar" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "une boisson (gazeuse)", en: "(soft/carbonated) drink/beverage" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "un café", en: "coffee" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "une eau (minérale)", en: "(mineral) water" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "un jus (d'orange, de pomme, etc.)", en: "(orange, apple, etc.) juice" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "le lait", en: "milk" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "une limonade", en: "lemon soda" },
  { unit: "Unité 4", lesson: "4B", category: "À table", fr: "un thé (glacé)", en: "(iced) tea" },
  // Expressions de quantité
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "(pas) assez (de)", en: "(not) enough (of)" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "beaucoup (de)", en: "a lot (of)" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "d'autres", en: "others" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "une bouteille (de)", en: "bottle (of)" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "un morceau (de)", en: "piece, bit (of)" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "un peu (plus/moins) (de)", en: "little (more/less) (of)" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "plusieurs", en: "several" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "quelque chose", en: "something; anything" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "quelques", en: "some" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "une tasse (de)", en: "cup (of)" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "trop (de)", en: "too many/much (of)" },
  { unit: "Unité 4", lesson: "4B", category: "Expressions de quantité", fr: "un verre (de)", en: "glass (of)" },
  // Au café
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "apporter", en: "to bring the check/bill" },
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "l'addition (f.)", en: "bill" },
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "coûter", en: "to cost" },
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "laisser un pourboire", en: "to leave a tip" },
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "Combien coûte(nt)...?", en: "How much is/are...?" },
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "un prix", en: "price" },
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "un serveur/une serveuse", en: "server" },
  { unit: "Unité 4", lesson: "4B", category: "Au café", fr: "Vous désirez?", en: "What do you want?/What would you like? (café)" },
  // Verbes
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "apprendre", en: "to learn" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "boire", en: "to drink" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "choisir", en: "to choose" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "comprendre", en: "to understand" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "finir", en: "to finish" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "grandir", en: "to grow" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "grossir", en: "to gain weight" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "maigrir", en: "to lose weight" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "obéir", en: "to obey" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "prendre", en: "to take; to have" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "réfléchir (à)", en: "to think (about), to reflect (on)" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "réussir (à)", en: "to succeed (in doing something)" },
  { unit: "Unité 4", lesson: "4B", category: "Verbes", fr: "rougir", en: "to blush" },
];

/* ==========================================================================
   GRAMMAR
   Each entry:
   {
     id, unit, lesson, code, title, goal,
     intro,                                   // "Point de départ" text
     blocks: [                                // explanation, in order
       { type:"text",  html }                 // a bullet/explanation (HTML allowed)
       { type:"conj",  caption, rows:[[form,gloss],...] }   // conjugation table
       { type:"ex",    items:[{fr,en},...] }  // example sentences
       { type:"table", caption, head:[...], rows:[[...],...] }  // reference table
     ],
     drillTitle,                              // "Essayez!" instructions
     drills: [ { q, a, note } ]               // q has "___" where the blank goes
   }
   ========================================================================== */
const GRAMMAR = [
  /* ---------------- 1A.2 ---------------- */
  {
    id: "1A2", unit: "Unité 1", lesson: "1A", code: "1A.2",
    title: "Numbers 0–60",
    goal: "Say how many items or people there are",
    intro: "Numbers in French follow patterns, as they do in English. Learn 0–30 first; the patterns help you learn 31–60.",
    blocks: [
      { type: "table", caption: "Numbers 0–30",
        head: ["0–10", "11–20", "21–30"],
        rows: [
          ["0 zéro", "—", "—"],
          ["1 un", "11 onze", "21 vingt et un"],
          ["2 deux", "12 douze", "22 vingt-deux"],
          ["3 trois", "13 treize", "23 vingt-trois"],
          ["4 quatre", "14 quatorze", "24 vingt-quatre"],
          ["5 cinq", "15 quinze", "25 vingt-cinq"],
          ["6 six", "16 seize", "26 vingt-six"],
          ["7 sept", "17 dix-sept", "27 vingt-sept"],
          ["8 huit", "18 dix-huit", "28 vingt-huit"],
          ["9 neuf", "19 dix-neuf", "29 vingt-neuf"],
          ["10 dix", "20 vingt", "30 trente"],
        ] },
      { type: "table", caption: "Numbers 31–60",
        head: ["31–34", "35–38", "39, 40, 50, 60"],
        rows: [
          ["31 trente et un", "35 trente-cinq", "39 trente-neuf"],
          ["32 trente-deux", "36 trente-six", "40 quarante"],
          ["33 trente-trois", "37 trente-sept", "50 cinquante"],
          ["34 trente-quatre", "38 trente-huit", "60 soixante"],
        ] },
      { type: "text", html: "When counting a series, use <b>un</b> for <i>one</i>. When <i>one</i> precedes a noun, use <b>un</b> with a masculine noun and <b>une</b> with a feminine noun (<i>un objet, une télévision</i>)." },
      { type: "text", html: "<b>21</b> = <b>vingt et un</b> (with <b>et</b>, no hyphen). Before a feminine noun, add <b>-e</b>: <i>vingt et une choses</i>." },
      { type: "text", html: "<b>31–39, 41–49, 51–59</b> follow the same pattern as 21–29 (e.g. <b>trente et un</b>, <b>trente-deux</b>). Add <b>-e</b> to <b>trente et un, quarante et un, cinquante et un</b> before a feminine noun." },
    ],
    drillTitle: "Write each number in French (words).",
    drills: [
      { q: "16 = ___", a: "seize", note: "11–20" },
      { q: "21 = ___", a: "vingt et un", note: "et, no hyphen" },
      { q: "29 = ___", a: "vingt-neuf", note: "21–30" },
      { q: "14 = ___", a: "quatorze", note: "11–20" },
      { q: "38 = ___", a: "trente-huit", note: "31–39" },
      { q: "40 = ___", a: "quarante", note: "tens" },
      { q: "47 = ___", a: "quarante-sept", note: "41–49" },
      { q: "52 = ___", a: "cinquante-deux", note: "51–59" },
      { q: "60 = ___", a: "soixante", note: "tens" },
    ],
  },

  /* ---------------- 1B.1 ---------------- */
  {
    id: "1B1", unit: "Unité 1", lesson: "1B", code: "1B.1",
    title: "Subject pronouns and the verb être",
    goal: "Say what objects and people are",
    intro: "The subject of a sentence is the person or thing that performs the action. The verb expresses the action. Subject pronouns replace a noun that is the subject.",
    blocks: [
      { type: "table", caption: "French subject pronouns",
        head: ["", "singular", "plural"],
        rows: [
          ["1st person", "je — I", "nous — we"],
          ["2nd person", "tu — you (fam.)", "vous — you (form. / pl.)"],
          ["3rd person", "il — he/it (m.) · elle — she/it (f.) · on — one", "ils — they (m./mixed) · elles — they (f.)"],
        ] },
      { type: "text", html: "Use <b>tu</b> for informal address and <b>vous</b> for formal. <b>vous</b> is also the plural form of <i>you</i>, both informal and formal." },
      { type: "text", html: "<b>on</b> refers to people in general (like English <i>one, they, you</i>) and can mean <i>we</i> in casual speech. <b>on</b> always takes the same verb form as <b>il</b> and <b>elle</b>." },
      { type: "text", html: "Use <b>ils</b> when replacing nouns that refer to a mixed group of males and females." },
      { type: "conj", caption: "être (to be)",
        rows: [
          ["je suis", "I am"], ["tu es", "you are"], ["il/elle/on est", "he/she/one is"],
          ["nous sommes", "we are"], ["vous êtes", "you are"], ["ils/elles sont", "they are"],
        ] },
      { type: "text", html: "<b>être</b> is irregular — its forms don't follow a pattern. The <b>-s</b> of <b>vous</b> is pronounced like <i>z</i> in <b>vous êtes</b> (liaison)." },
      { type: "ex", items: [
        { fr: "Vous êtes à Paris.", en: "You are in Paris." },
        { fr: "L'enseignant parle français.", en: "The teacher speaks French." },
      ] },
      { type: "text", html: "Use <b>c'est</b> (+ article + noun) or <b>ce sont</b> to identify who or what something is. Always use an article before the noun — unless it's a proper name." },
      { type: "ex", items: [
        { fr: "C'est un téléphone.", en: "That's a phone." },
        { fr: "Ce sont des photos.", en: "Those are pictures." },
        { fr: "C'est Anya.", en: "That's Anya." },
      ] },
      { type: "text", html: "Use <b>il/elle est</b> and <b>ils/elles sont</b> to refer to someone or something already mentioned, and to give a profession or relationship — with <u>no article</u> before the profession." },
      { type: "ex", items: [
        { fr: "Elle est moderne.", en: "It's modern." },
        { fr: "Il est acteur.", en: "He's an actor." },
        { fr: "Elles sont amies.", en: "They are friends." },
      ] },
    ],
    drillTitle: "Fill in the blanks with the correct forms of the verb être.",
    drills: [
      { q: "Je ___ ici.", a: "suis", note: "je" },
      { q: "Ils ___ intelligents.", a: "sont", note: "ils" },
      { q: "Tu ___ étudiante.", a: "es", note: "tu" },
      { q: "Nous ___ à Québec.", a: "sommes", note: "nous" },
      { q: "Vous ___ Mme Lacroix?", a: "êtes", note: "vous" },
      { q: "Marie ___ chanteuse.", a: "est", note: "elle" },
    ],
  },

  /* ---------------- 1B.2 ---------------- */
  {
    id: "1B2", unit: "Unité 1", lesson: "1B", code: "1B.2",
    title: "Adjective agreement",
    goal: "Describe people, places, and things",
    intro: "Adjectives describe people, places, and things, and are often used with être to point out qualities. Many French adjectives are cognates of English words.",
    blocks: [
      { type: "text", html: "Most French adjectives <b>agree in number and gender</b> with the noun they modify. To make an adjective feminine, add <b>-e</b> to the masculine form. If it already ends in an unaccented <b>-e</b>, add nothing (<i>agréable, optimiste, sympathique</i>)." },
      { type: "text", html: "To make an adjective plural, add <b>-s</b>. Use the masculine plural for a mixed group. <i>Marc et David sont intelligents. · Anne et Claire sont intelligentes.</i>" },
      { type: "table", caption: "Agreement of patient",
        head: ["", "singular", "plural"],
        rows: [
          ["masculine", "patient", "patients"],
          ["feminine", "patiente", "patientes"],
        ] },
      { type: "text", html: "French adjectives usually come <b>after</b> the noun they modify (when not directly after a form of <b>être</b>). <i>Ce sont des élèves brillantes. · Bernard est un homme agréable et poli.</i>" },
      { type: "text", html: "<b>Adjectives of nationality</b> are not capitalized. Add <b>-ne</b> to masculine forms ending in <b>-ien</b> to make them feminine (<i>canadien → canadienne</i>); add <b>-e</b> to most others." },
      { type: "ex", items: [
        { fr: "Il est américain.", en: "He is American." },
        { fr: "Elle est française.", en: "She is French." },
      ] },
      { type: "text", html: "Adjectives that already end in <b>-s</b> (like <i>sénégalais</i>) keep the same masculine singular and plural form, but add <b>-e</b> for the feminine (<i>sénégalaise</i>) and <b>-es</b> for the feminine plural." },
      { type: "text", html: "To ask nationality/heritage: <b>Quelle est ta/votre nationalité?</b> or <b>Tu es / Vous êtes de quelle origine?</b> Adjectives after <b>nationalité</b> and <b>origine</b> are feminine (both nouns are feminine): <i>Je suis de nationalité canadienne.</i>" },
    ],
    drillTitle: "Write in the correct forms of the adjectives.",
    drills: [
      { q: "Natalie est ___ (brillant).", a: "brillante", note: "fem. sing." },
      { q: "Ils sont ___ (anglais).", a: "anglais", note: "masc. pl. (ends in -s)" },
      { q: "Elle adore la littérature ___ (indien).", a: "indienne", note: "fem. (-ien → -ienne)" },
      { q: "Les actrices sont ___ (impatient).", a: "impatientes", note: "fem. pl." },
      { q: "Christelle est ___ (amusant).", a: "amusante", note: "fem. sing." },
      { q: "Les élèves sont ___ (poli) en cours.", a: "polis", note: "masc./mixed pl." },
      { q: "Mme Castillon est très ___ (occupé).", a: "occupée", note: "fem. sing." },
      { q: "Luc et moi, nous sommes ___ (sincère).", a: "sincères", note: "pl. (ends in -e)" },
    ],
  },

  /* ---------------- 2A.1 ---------------- */
  {
    id: "2A1", unit: "Unité 2", lesson: "2A", code: "2A.1",
    title: "Present tense of regular -er verbs",
    goal: "Describe familiar actions and daily activities",
    intro: "The infinitives of most French verbs end in -er. To form the present tense, drop the -er from the infinitive and add the endings for each subject pronoun.",
    blocks: [
      { type: "conj", caption: "parler (to speak)",
        rows: [
          ["je parle", "I speak"], ["tu parles", "you speak"], ["il/elle/on parle", "he/she/one speaks"],
          ["nous parlons", "we speak"], ["vous parlez", "you speak"], ["ils/elles parlent", "they speak"],
        ] },
      { type: "text", html: "The endings are <b>-e, -es, -e, -ons, -ez, -ent</b>. Other verbs conjugated like <b>parler</b>: aimer, arriver, chercher, dessiner, donner, étudier, habiter, oublier, regarder, rencontrer, retrouver, travailler." },
      { type: "text", html: "<b>je</b> becomes <b>j'</b> before a vowel sound: <i>J'habite à Bruxelles.</i> The present tense translates as <i>I speak</i>, <i>I am speaking</i>, or <i>I do speak</i>." },
      { type: "text", html: "With <b>adorer, aimer,</b> and <b>détester</b>, use the definite article before a noun (<i>J'aime mieux l'art.</i>), and use the infinitive to say you like/hate doing something (<i>Ils adorent travailler.</i>)." },
      { type: "text", html: "<b>Spelling changes:</b> verbs in <b>-ger</b> add an <b>e</b> in the <b>nous</b> form (so g stays soft); verbs in <b>-cer</b> change c to <b>ç</b> in the <b>nous</b> form." },
      { type: "conj", caption: "manger (to eat) — nous form",
        rows: [
          ["je mange", "I eat"], ["tu manges", "you eat"], ["il/elle/on mange", "he/she/one eats"],
          ["nous mangeons", "we eat ← +e"], ["vous mangez", "you eat"], ["ils/elles mangent", "they eat"],
        ] },
      { type: "conj", caption: "commencer (to begin) — nous form",
        rows: [
          ["je commence", "I begin"], ["tu commences", "you begin"], ["il/elle/on commence", "he/she/one begins"],
          ["nous commençons", "we begin ← ç"], ["vous commencez", "you begin"], ["ils/elles commencent", "they begin"],
        ] },
      { type: "text", html: "<b>Commands:</b> drop the subject pronoun. The <b>tu</b> command of -er verbs drops the <b>-s</b> (<i>Regarde le tableau!</i>). The <b>être</b> commands are irregular: <b>sois, soyons, soyez</b>." },
    ],
    drillTitle: "Complete the sentences with the correct present-tense forms of the verbs.",
    drills: [
      { q: "Je ___ français en classe.", a: "parle", note: "parler" },
      { q: "Nous ___ près de l'école.", a: "habitons", note: "habiter" },
      { q: "Ils ___ le cours de sciences politiques.", a: "aiment", note: "aimer" },
      { q: "Vous ___ en classe?!", a: "mangez", note: "manger" },
      { q: "Le cours ___ à huit heures.", a: "commence", note: "commencer" },
      { q: "Marie-Claire ___ un stylo.", a: "cherche", note: "chercher" },
      { q: "Nous ___ un crayon en cours de maths.", a: "partageons", note: "partager (-ger)" },
    ],
  },

  /* ---------------- 2A.2 ---------------- */
  {
    id: "2A2", unit: "Unité 2", lesson: "2A", code: "2A.2",
    title: "Forming questions and expressing negation",
    goal: "Ask and answer questions about daily life",
    intro: "There are four main ways to ask a question in French, and a simple pattern for making sentences negative.",
    blocks: [
      { type: "text", html: "<b>1. Rising intonation</b> — say a statement with your voice rising, and write a question mark. Informal. <i>Vous habitez à Bordeaux?</i>" },
      { type: "text", html: "<b>2. Est-ce que…</b> placed before a statement (<b>Est-ce qu'</b> before a vowel sound). Somewhat informal. <i>Est-ce que vous parlez français?</i>" },
      { type: "text", html: "<b>3. Tag questions</b> at the end: <b>n'est-ce pas?</b> (isn't that right?), <b>non?</b>, <b>d'accord?</b> (OK?). Informal. <i>Nous mangeons bientôt, n'est-ce pas?</i>" },
      { type: "text", html: "<b>4. Inversion</b> — invert the subject pronoun and verb with a hyphen. If the verb ends in a vowel and the pronoun is <b>il/elle/on</b>, insert <b>-t-</b>. Formal/written. <i>Parlez-vous français? · Mange-t-il à la cantine?</i>" },
      { type: "text", html: "Only subject pronouns can be inverted. If the subject is a noun, add the matching pronoun: <i>Nina arrive-t-elle demain?</i> Note: <b>il y a → y a-t-il</b>, and <b>c'est → est-ce</b>." },
      { type: "text", html: "Use <b>pourquoi</b> to ask <i>why?</i> and answer with <b>parce que</b> (<b>parce qu'</b> before a vowel)." },
      { type: "text", html: "<b>Negation:</b> place <b>ne</b> (<b>n'</b> before a vowel sound) before the conjugated verb and <b>pas</b> after it." },
      { type: "ex", items: [
        { fr: "Je ne dessine pas bien.", en: "I don't draw well." },
        { fr: "Elles n'étudient pas.", en: "They're not studying." },
        { fr: "Abdel n'aime pas étudier.", en: "Abdel doesn't like to study." },
        { fr: "Ne détestez-vous pas travailler?", en: "Don't you hate to work?" },
      ] },
      { type: "table", caption: "Expressions of agreement and disagreement",
        head: ["agreement", "disagreement"],
        rows: [
          ["oui — yes", "(mais) non — no (but of course not)"],
          ["bien sûr — of course", "pas du tout — not at all"],
          ["moi/toi non plus — me/you neither", "peut-être — maybe, perhaps"],
        ] },
      { type: "text", html: "Use <b>si</b> instead of <b>oui</b> to contradict a negative question. <i>— Ne parles-tu pas à Daniel? — Si!</i> (Yes I am!)" },
    ],
    drillTitle: "Rewrite 1–4 as questions using est-ce que, and 5–8 using inversion.",
    drills: [
      { q: "Vous mangez à la cantine. → ___", a: "Est-ce que vous mangez à la cantine?", note: "est-ce que" },
      { q: "Ils adorent les devoirs. → ___", a: "Est-ce qu'ils adorent les devoirs?", note: "est-ce qu' (vowel)" },
      { q: "La biologie est difficile. → ___", a: "Est-ce que la biologie est difficile?", note: "est-ce que" },
      { q: "Tu travailles. → ___", a: "Est-ce que tu travailles?", note: "est-ce que" },
      { q: "Vous arrivez demain. → ___", a: "Arrivez-vous demain?", note: "inversion" },
      { q: "Il y a deux salles de classe. → ___", a: "Y a-t-il deux salles de classe?", note: "il y a → y a-t-il" },
      { q: "Ils n'habitent pas à Québec. → ___", a: "N'habitent-ils pas à Québec?", note: "inversion + negation" },
      { q: "C'est le professeur d'art. → ___", a: "Est-ce le professeur d'art?", note: "c'est → est-ce" },
    ],
  },

  /* ---------------- 2B.1 ---------------- */
  {
    id: "2B1", unit: "Unité 2", lesson: "2B", code: "2B.1",
    title: "Present tense of avoir",
    goal: "Discuss basic feelings and needs using the verb avoir",
    intro: "The verb avoir (to have) is used frequently. Its present-tense forms are irregular, so memorize each one.",
    blocks: [
      { type: "conj", caption: "avoir (to have)",
        rows: [
          ["j'ai", "I have"], ["tu as", "you have"], ["il/elle/on a", "he/she/one has"],
          ["nous avons", "we have"], ["vous avez", "you have"], ["ils/elles ont", "they have"],
        ] },
      { type: "text", html: "Liaison is required between <b>on, nous, vous, ils, elles</b> and the verb form that follows: pronounce the final <b>-s</b> as a <i>z</i> (<i>nous avons, ils ont</i>)." },
      { type: "text", html: "After a negation, an indefinite article (un, une, des) usually becomes <b>de / d'</b>. <i>J'ai un cours. → Je n'ai pas de cours.</i>" },
      { type: "text", html: "<b>avoir</b> appears in many set expressions where English uses <i>to be</i> or <i>to feel</i>:" },
      { type: "table", caption: "Expressions with avoir",
        head: ["", ""],
        rows: [
          ["avoir… ans — to be… years old", "avoir de bonnes/mauvaises notes — to have good/bad grades"],
          ["avoir besoin (de) — to need", "avoir peur (de) — to be afraid (of)"],
          ["avoir chaud — to be hot", "avoir raison — to be right"],
          ["avoir envie (de) — to feel like", "avoir sommeil — to be sleepy"],
          ["avoir froid — to be cold", "avoir tort — to be wrong"],
        ] },
      { type: "text", html: "<b>avoir besoin de</b>, <b>avoir peur de</b>, and <b>avoir envie de</b> can be followed by either a noun or a verb. <i>J'ai besoin d'une calculatrice. · J'ai besoin d'étudier.</i>" },
      { type: "text", html: "Command forms are irregular: <b>aie, ayons, ayez</b>. Place <b>ne … pas</b> around the command for the negative. <i>N'ayez pas peur.</i>" },
    ],
    drillTitle: "Complete the sentences with the correct forms of avoir.",
    drills: [
      { q: "La température est de 35°C. Nous ___ chaud.", a: "avons", note: "nous" },
      { q: "En Alaska, en décembre, vous ___ froid.", a: "avez", note: "vous" },
      { q: "Martine ___ envie de danser.", a: "a", note: "elle" },
      { q: "Ils ___ besoin d'une calculatrice pour le devoir.", a: "ont", note: "ils" },
      { q: "Est-ce que tu ___ peur des insectes?", a: "as", note: "tu" },
      { q: "Il ___ raison.", a: "a", note: "il" },
      { q: "J'___ cours d'économie le lundi.", a: "ai", note: "je → j'" },
      { q: "Ils ___ sommeil.", a: "ont", note: "ils" },
      { q: "Mohammed ___ deux cousins à Marseille.", a: "a", note: "il" },
      { q: "Vous ___ un grand appartement.", a: "avez", note: "vous" },
    ],
  },

  /* ---------------- 2B.2 ---------------- */
  {
    id: "2B2", unit: "Unité 2", lesson: "2B", code: "2B.2",
    title: "Telling time",
    goal: "Ask and answer questions about time of day",
    intro: "You use the verb être with numbers to tell time. Ask the time with Quelle heure est-il?",
    blocks: [
      { type: "text", html: "<b>On the hour:</b> [number] + <b>heures</b>. Use <b>une heure</b> for one o'clock. <i>Il est six heures. · Il est une heure.</i>" },
      { type: "text", html: "<b>Hour to half-hour:</b> state the minutes past the hour. <i>Il est neuf heures cinq. · Il est onze heures vingt.</i>" },
      { type: "text", html: "<b>et quart</b> = quarter past (15 min); <b>et demie</b> = half past (30 min). <i>Il est sept heures et quart. · Il est six heures et demie.</i>" },
      { type: "text", html: "<b>Half-hour to the hour:</b> use <b>moins</b> (minus) and subtract from the next hour. <i>Il est trois heures moins dix. · Il est une heure moins le quart.</i>" },
      { type: "text", html: "To say <i>at</i> what time something happens, use the preposition <b>à</b>. <i>Le cours commence à neuf heures.</i>" },
      { type: "table", caption: "Expressions for telling time",
        head: ["", ""],
        rows: [
          ["à quelle heure? — (at) what time/when?", "midi — noon"],
          ["de l'après-midi — in the afternoon", "minuit — midnight"],
          ["du matin — in the morning", "pile — sharp, on the dot"],
          ["du soir — in the evening", "presque — almost"],
          ["en avance — early", "tard / tôt — late / early"],
          ["en retard — late", "vers — about"],
        ] },
      { type: "text", html: "French has <u>no</u> a.m./p.m. — use <b>du matin</b>, <b>de l'après-midi</b>, <b>du soir</b>. The <b>24-hour clock</b> is used for official time, with only plain numbers (no <i>et demie</i>, <i>moins le quart</i>): <i>Le film est à vingt-deux heures trente-sept (10:37 p.m.).</i>" },
      { type: "text", html: "When writing times with digits, separate the hour and minutes with <b>h</b> (for <i>heure</i>) instead of a colon: <b>3h25, 11h10, 21h45</b>." },
    ],
    drillTitle: "Write out the correct times (in words) according to the cues.",
    drills: [
      { q: "(1:00 a.m.) Il est ___ du matin.", a: "une heure", note: "on the hour" },
      { q: "(2:50 a.m.) Il est ___ du matin.", a: "trois heures moins dix", note: "moins" },
      { q: "(8:30 p.m.) Il est ___ du soir.", a: "huit heures et demie", note: "et demie" },
      { q: "(10:08 a.m.) Il est ___ du matin.", a: "dix heures huit", note: "minutes past" },
      { q: "(7:15 p.m.) Il est ___ du soir.", a: "sept heures et quart", note: "et quart" },
      { q: "(4:05 p.m.) Il est ___ de l'après-midi.", a: "quatre heures cinq", note: "minutes past" },
      { q: "(4:45 a.m.) Il est ___ du matin.", a: "cinq heures moins le quart", note: "moins le quart" },
      { q: "(3:20 a.m.) Il est ___ du matin.", a: "trois heures vingt", note: "minutes past" },
      { q: "(12:00 a.m.) Il est ___.", a: "minuit", note: "midnight" },
    ],
  },

  /* ---------------- 4A.1 ---------------- */
  {
    id: "4A1", unit: "Unité 4", lesson: "4A", code: "4A.1",
    title: "The verb aller",
    goal: "Talk about the near future and going places",
    intro: "You saw a form of aller (to go) in ça va. Now use it to talk about going places and about actions in the immediate future.",
    blocks: [
      { type: "conj", caption: "aller (to go)",
        rows: [
          ["je vais", "I go"], ["tu vas", "you go"], ["il/elle/on va", "he/she/one goes"],
          ["nous allons", "we go"], ["vous allez", "you go"], ["ils/elles vont", "they go"],
        ] },
      { type: "text", html: "<b>aller</b> is irregular — only the <b>nous</b> and <b>vous</b> forms resemble the infinitive." },
      { type: "text", html: "<b>Le futur proche</b> (the immediate future): use the present tense of <b>aller</b> + an infinitive to say what <i>is going to</i> happen. <i>Nous allons déjeuner. (We're going to have lunch.)</i>" },
      { type: "text", html: "To make <b>le futur proche</b> negative, place <b>ne/n'</b> before the form of <b>aller</b> and <b>pas</b> after it. <i>Je ne vais pas oublier la date.</i>" },
      { type: "text", html: "<b>The preposition à</b> contracts with the definite article: <b>à + le → au</b>, <b>à + les → aux</b>. It does <u>not</u> contract with <b>la</b> or <b>l'</b> (stays <b>à la</b>, <b>à l'</b>)." },
      { type: "ex", items: [
        { fr: "Nous allons au magasin.", en: "We're going to the store." },
        { fr: "Ils parlent aux profs.", en: "They're talking to the teachers." },
        { fr: "Je rentre à la maison.", en: "I'm going back home." },
        { fr: "Il va à l'épicerie.", en: "He's going to the grocery store." },
      ] },
      { type: "table", caption: "Verbs with the preposition à",
        head: ["", ""],
        rows: [
          ["commencer à + [infinitive] — to start doing", "penser à — to think about"],
          ["parler à — to talk to", "téléphoner à — to phone (someone)"],
        ] },
      { type: "text", html: "In general <b>à</b> means <i>at/in</i>, while <b>dans</b> means <i>inside/within</i>. Learn the preposition that goes with each place name." },
      { type: "table", caption: "Prepositions with place names",
        head: ["with à", "with dans"],
        rows: [
          ["à la maison — at home", "dans la maison — inside the house"],
          ["à Paris — in Paris", "dans Paris — within Paris"],
          ["en ville — in town", "dans la ville — within the town"],
          ["sur la place — in the square", "à/sur la terrasse — on the terrace"],
        ] },
    ],
    drillTitle: "1–4: correct form of aller. 5–8: correct preposition + definite article (au, aux, à la, à l').",
    drills: [
      { q: "Comment ça ___?", a: "va", note: "aller" },
      { q: "Tu ___ nager.", a: "vas", note: "aller" },
      { q: "Ils ___ étudier chez Élodie.", a: "vont", note: "aller" },
      { q: "Nous ___ travailler au café.", a: "allons", note: "aller" },
      { q: "Vous mangez ___ restaurant ce soir?", a: "au", note: "à + le" },
      { q: "Elle est ___ église dimanche matin.", a: "à l'", note: "à + l' (vowel)" },
      { q: "Le soir, je rentre ___ maison à sept heures.", a: "à la", note: "à + la" },
      { q: "Est-ce que le prof parle ___ élèves?", a: "aux", note: "à + les" },
    ],
  },

  /* ---------------- 4A.2 ---------------- */
  {
    id: "4A2", unit: "Unité 4", lesson: "4A", code: "4A.2",
    title: "Interrogative words",
    goal: "Ask and answer information questions",
    intro: "Besides yes/no questions, many questions seek information. Use interrogative words with est-ce que or inversion to ask for specifics.",
    blocks: [
      { type: "table", caption: "Interrogative words",
        head: ["", ""],
        rows: [
          ["à quelle heure? — at what time?", "quand? — when?"],
          ["combien (de)? — how many?/how much?", "que/qu'…? — what?"],
          ["comment? — how?/what?", "quel(le)(s)? — which?/what?"],
          ["où? — where?", "(à/avec/pour) qui? — (to/with/for) who(m)?"],
          ["pourquoi? — why?", "quoi? — what?"],
        ] },
      { type: "text", html: "A very informal option is to place the interrogative word <b>after</b> the verb: <i>Tu t'appelles comment? · Tu habites où?</i>" },
      { type: "text", html: "When <b>qui</b> (who) is the <u>subject</u>, follow it directly with a 3rd-person singular verb: <i>Qui invite Patrice à dîner?</i> When <b>qui</b> (whom) is the <u>object</u>, follow it with <b>est-ce que</b> + subject/verb or with inversion: <i>Qui est-ce que tu regardes? / Qui regardes-tu?</i>" },
      { type: "text", html: "<b>quand?</b> and <b>à quelle heure?</b> both mean <i>when?</i> — use <b>quand</b> for a day/date, <b>à quelle heure</b> for a specific time of day." },
      { type: "text", html: "<b>que/qu'</b> (what) with est-ce que or inversion is always followed by a subject and verb: <i>Que regardons-nous? · Qu'est-ce que tu vas manger?</i>" },
      { type: "text", html: "<b>quoi</b> (what) is used after a preposition (+ est-ce que / inversion), or after the verb in informal questions with no preposition: <i>À quoi penses-vous? · Elle étudie quoi?</i> Say <b>Comment?</b> or <b>Pardon?</b> (informally <b>Quoi?</b>) when you don't understand." },
      { type: "table", caption: "The interrogative adjective quel(le)(s)",
        head: ["", "singular", "plural"],
        rows: [
          ["masculine", "quel", "quels"],
          ["feminine", "quelle", "quelles"],
        ] },
      { type: "text", html: "<b>quel</b> means <i>what</i> or <i>which</i> and agrees in gender and number with the noun: <i>Quel restaurant aimes-tu? · Quelles filles vont à la cantine?</i> Use <b>quel + être + noun</b> (<i>Quel est ton numéro de téléphone?</i>), and <b>qu'est-ce que</b> in most other cases. As an exclamation: <i>Quel beau garçon! · Quelles grandes maisons!</i>" },
    ],
    drillTitle: "Give the interrogative word(s) that complete each question.",
    drills: [
      { q: "___ allez-vous?", a: "Comment", note: "how are you" },
      { q: "___ est-ce que vous allez faire après le cours?", a: "Qu'", note: "Qu'est-ce que" },
      { q: "___ est-ce que tu ne travailles pas?", a: "Pourquoi", note: "why" },
      { q: "Avec ___ est-ce qu'on va au cinéma ce soir?", a: "qui", note: "with whom" },
      { q: "___ d'élèves y a-t-il?", a: "Combien", note: "how many" },
      { q: "___ musées vas-tu visiter?", a: "Quels", note: "quel + masc. pl." },
      { q: "___ est-ce qu'on dîne ce soir?", a: "Où", note: "where" },
      { q: "De ___ parlez-vous?", a: "quoi", note: "after preposition" },
    ],
  },
];
